"""
Django settings for cash_agance_proj project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os  # Wuxuu Django ka caawiyaa inuu la hadlo nidaamka computer-ka (Operating System)
from pathlib import Path  # Wuxuu maamulaa dariiqyada (paths) faylalka software-ka
from dotenv import load_dotenv  # Wuxuu soo roraa maktabadii akhrin lahayd faylka .env
load_dotenv()  # Sadarkan wuxuu amar siinayaa Django inuu hadda akhriyo xogta ku dhex jirta faylka .env
SECRET_KEY = os.getenv('SECRET_KEY')  
# Wuxuu leeyahay: "Tag .env, ka raadi erayga 'SECRET_KEY', wixii ku horgudban u dhiib Django"
DEBUG = os.getenv('DEBUG') == 'True'  
# .env xogta uu soo celiyo mar walba waa qoraal (String). 
# Sadarkaan wuxuu leeyahay: "Haddii DEBUG uu la mid yahay qoraalka 'True', ka dhig True (Boolean), haddii kalena ka dhig False."

# Marka hore waxaan ka soo akhrineynaa liiska .env dhexdiisa ku jira
hosts_input = os.getenv('ALLOWED_HOSTS')

if hosts_input:
    # Haddii .env laga helo magacyo, waxaan u kala jebineynaa (split) meeshii kooma (,) ay ku taal si ay u noqoto Liis [List]
    ALLOWED_HOSTS = hosts_input.split(',')
else:
    # Haddii sabab kasta faylka .env loo waayo, ku shaqee kuwan caadiga ah si uusan barnaamijku u istaagin
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Ammaanka deegaanka rasmiga ah (Production)
if not DEBUG:
    # 1. Ku qasbida HTTPS mar walba
    SECURE_SSL_REDIRECT = True
    
    # 2. Sugidda amniga Cookies-ka (Session iyo CSRF)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # 3. Kicinta nidaamka adag ee HSTS (1 sano)
    SECURE_HSTS_SECONDS = 31536000  # Muddo 1 sano ah oo ilbiriqsiyo ah
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Luuqadda (waad iska deyn kartaa en-us)
LANGUAGE_CODE = 'en-us'

# Bedel 'UTC' una beddel 'Africa/Mogadishu'
TIME_ZONE = 'Africa/Mogadishu'

# Tan ka dhig True si Django u maamulo waqtiga gudaha
USE_I18N = True

# Tan aad ugu fiirso: Haddii ay True tahay, Django wuxuu database-ka ku kaydiyaa UTC 
# laakiin Template-ka wuxuu ku tusi doonaa saacadda Soomaaliya.
USE_TZ = True
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!

LOGIN_URL = 'login'
# SECURITY WARNING: don't run with debug turned on in production!





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cash_agance_proj.urls'
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cash_agance_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
